### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by Yukino-3** [ChangLee0903/SERIL#2]
Hi, thanks for your code sharing. I meet an error during the inference.
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    main()
  File "main.py", line 84, in main
    test(args, config)
  File "~/Pycharmproject/SERIL/evaluation.py", line 151, in test
    results[i][0, Ti] = score[i]
UnboundLocalError: local variable 'results' referenced before assignment

Does anyone know how to fix that?

**Comment by ChangLee0903** [comment]
Hi @Yukino-3 ,

Sorry for my late replying. 
While your set your testing noisy dataset properly, the task_num variable will not be zero, and hence the model_list will not be a null list. To this end, the UnboundLocalError issue might be solved.
![image](https://user-images.githubusercontent.com/68819118/169919336-50ee9faf-cf06-49f8-9c87-c738930885d0.png)
Seems that you did not set your path of testing noisy dataset properly.
